### ISSUE TITLE
TOML dependencies required for coverage

### ISSUE THREAD

**Issue by astrochun** [ewjoachim/python-coverage-comment-action#12]
Hi, I'm glad that you built this GitHub Actions. I tried using it recently on a python 3.10 app and came across the following issue. 

```python
/usr/bin/docker run --name ewjoachimpythoncoveragecommentactionlatest_884cb6 --label 08450d --workdir /github/workspace --rm -e pythonLocation -e LD_LIBRARY_PATH -e INPUT_GITHUB_TOKEN -e INPUT_GITHUB_PR_RUN_ID -e INPUT_COMMENT_TEMPLATE -e INPUT_BADGE_FILENAME -e INPUT_COMMENT_ARTIFACT_NAME -e INPUT_COMMENT_FILENAME -e INPUT_MINIMUM_GREEN -e INPUT_MINIMUM_ORANGE -e INPUT_MERGE_COVERAGE_FILES -e INPUT_VERBOSE -e GITHUB_TOKEN -e GITHUB_PR_RUN_ID -e BADGE_FILENAME -e COMMENT_ARTIFACT_NAME -e COMMENT_FILENAME -e MINIMUM_GREEN -e MINIMUM_ORANGE -e MERGE_COVERAGE_FILES -e VERBOSE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/fastapi-oauth-dev/fastapi-oauth-dev":"/github/workspace" ewjoachim/python-coverage-comment-action:latest
INFO:coverage_comment:Starting action
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/subprocess.py", line [16](https://github.com/astrochun/fastapi-oauth-dev/runs/6396946762?check_suite_focus=true#step:8:16), in run
    return subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('coverage', 'json', '-o', '-')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/coverage_comment", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/main.py", line 37, in main
    exit_code = action(
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/main.py", line 67, in action
    coverage = coverage_module.get_coverage_info(merge=config.MERGE_COVERAGE_FILES)
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/coverage.py", line 68, in get_coverage_info
    json_coverage = subprocess.run("coverage", "json", "-o", "-")
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/subprocess.py", line [24](https://github.com/astrochun/fastapi-oauth-dev/runs/6396946762?check_suite_focus=true#step:8:24), in run
    raise SubProcessError("/n".join([exc.stdout, exc.stderr])) from exc
coverage_comment.subprocess.SubProcessError: Can't read 'pyproject.toml' without TOML support. Install with [toml] extra
/n
```

This may be as simple as updating the dependencies but a bit surprised since your code also includes a `pyproject.toml`

**Comment by ewjoachim** [comment]
I wonder what changed and caused this in https://coverage.readthedocs.io/en/6.3.2/changes.html ...

Do you want to give it a shot with a PR ?

**Comment by astrochun** [comment]
> I wonder what changed and caused this in https://coverage.readthedocs.io/en/6.3.2/changes.html ...
> 
> Do you want to give it a shot with a PR ?

It's weird because my unit test uses `coverage` and there was no `toml` error (even though I didn't specify `coveage[toml]`). I forked and created a patch but the thing is, I tried to re-run the CI with my forked copy (on the hotfix branch) and it still gave me the same error. What's also weird is that it is still pulling in your action instead (perhaps a caching thing)

![Screen Shot 2022-05-12 at 3 13 18 PM](https://user-images.githubusercontent.com/20305734/168176412-5d66433c-c8f5-4dbd-87c0-e46e34cc9f4c.png)

**Comment by astrochun** [comment]
It seems that the `toml` issue may have been resolved as the error I receive is a different one (may be a packaging issue):
```python
Traceback (most recent call last):
  File "/usr/local/bin/coverage_comment", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/main.py", line 37, in main
    exit_code = action(
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/main.py", line 67, in action
    coverage = coverage_module.get_coverage_info(merge=config.MERGE_COVERAGE_FILES)
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/coverage.py", line 68, in get_coverage_info
    json_coverage = subprocess.run("coverage", "json", "-o", "-")
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/subprocess.py", line 24, in run
    raise SubProcessError("/n".join([exc.stdout, exc.stderr])) from exc
coverage_comment.subprocess.SubProcessError: No source for code: '/home/runner/work/fastapi-oauth-dev/fastapi-oauth-dev/fastapi_oauth_dev/__init__.py'.
```

**Comment by ewjoachim** [comment]
I can't guarantee that I'll have enough time to tackle this in the near future. 

> What's also weird is that it is still pulling in your action instead

I think that's because the action mainly pulls the existing docker image that is pushed to docker hub. I guess we're missing a step that says that when targetting a branch, we need to build the docker image instead.
See https://github.com/ewjoachim/python-coverage-comment-action/blob/v2/action.yml#L67

**Comment by astrochun** [comment]
Thanks for the clarification. This issue is one that has been encountered with `coverage` (see https://stackoverflow.com/questions/2386975/no-source-for-code-message-in-coverage-py). A `-i` flag may be the fix issue.

**Comment by astrochun** [comment]
Thanks again for your help. I identified the issue and it was able to resolve it.
