### ISSUE TITLE
Failed to generate comment for PR

### ISSUE THREAD

**Issue by crazyscientist** [ewjoachim/python-coverage-comment-action#48]
While setting up the action as described in the [docs](https://github.com/marketplace/actions/python-coverage-comment), I came across this traceback.

I'm not sure, whether I missed something or whether there is an actual problem :thinking: 
```
Run ewjoachim/python-coverage-comment-action@v2
  with:
    GITHUB_TOKEN: ***
    MERGE_COVERAGE_FILES: true
    VERBOSE: true
    BADGE_FILENAME: python-coverage-comment-action-badge.json
    COMMENT_ARTIFACT_NAME: python-coverage-comment-action
    COMMENT_FILENAME: python-coverage-comment-action.txt
    MINIMUM_GREEN: 100
    MINIMUM_ORANGE: 70
/usr/bin/docker run --name ewjoachimpythoncoveragecommentactionv2_52b40a --label 94859b --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_MERGE_COVERAGE_FILES -e INPUT_VERBOSE -e INPUT_GITHUB_PR_RUN_ID -e INPUT_COMMENT_TEMPLATE -e INPUT_BADGE_FILENAME -e INPUT_COMMENT_ARTIFACT_NAME -e INPUT_COMMENT_FILENAME -e INPUT_MINIMUM_GREEN -e INPUT_MINIMUM_ORANGE -e GITHUB_TOKEN -e GITHUB_PR_RUN_ID -e COMMENT_TEMPLATE -e BADGE_FILENAME -e COMMENT_ARTIFACT_NAME -e COMMENT_FILENAME -e MINIMUM_GREEN -e MINIMUM_ORANGE -e MERGE_COVERAGE_FILES -e VERBOSE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_TRIGGERING_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/osc-tiny/osc-tiny":"/github/workspace" ewjoachim/python-coverage-comment-action:v2
INFO:coverage_comment:Starting action
DEBUG:coverage_comment:Settings: Config(GITHUB_BASE_REF='master', GITHUB_REPOSITORY='crazyscientist/osc-tiny', GITHUB_REF='refs/pull/79/merge', GITHUB_EVENT_NAME='pull_request', GITHUB_PR_RUN_ID=None, COMMENT_TEMPLATE='', BADGE_FILENAME=PosixPath('python-coverage-comment-action-badge.json'), COMMENT_ARTIFACT_NAME='python-coverage-comment-action', COMMENT_FILENAME=PosixPath('python-coverage-comment-action.txt'), MINIMUM_GREEN=100.0, MINIMUM_ORANGE=70.0, MERGE_COVERAGE_FILES=True, VERBOSE=True)
DEBUG:coverage_comment:Operating on refs/pull/79/merge
INFO:coverage_comment:Generating comment for PR
DEBUG:httpx._client:HTTP Request: GET https://raw.githubusercontent.com/wiki/crazyscientist/osc-tiny/python-coverage-comment-action-badge.json "HTTP/1.1 404 Not Found"
DEBUG:coverage_comment:Exception while getting previous coverage data, attempting to download the file directly from the git repository (assuming the wiki is private).
DEBUG:coverage_comment:Unhandled error occurred when cloning wiki.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/wiki.py", line 85, in get_file_contents
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://raw.githubusercontent.com/wiki/crazyscientist/osc-tiny/python-coverage-comment-action-badge.json'
For more information check: https://httpstatuses.com/404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/subprocess.py", line 16, in run
    return subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('git', 'clone', '***github.com/crazyscientist/osc-tiny.wiki.git', '.')' returned non-zero exit status 128.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/subprocess.py", line 32, in _git
    return run(
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/subprocess.py", line 24, in run
    raise SubProcessError("/n".join([exc.stdout, exc.stderr])) from exc
coverage_comment.subprocess.SubProcessError: /nCloning into '.'...
fatal: remote error: access denied or repository not exported: /d/nw/d1/86/6a/195882036/161181449.wiki.git


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/wiki.py", line 26, in cloned_wiki
    git.clone(
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/subprocess.py", line 39, in _git
    raise GitError from exc
coverage_comment.subprocess.GitError
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/wiki.py", line 85, in get_file_contents
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://raw.githubusercontent.com/wiki/crazyscientist/osc-tiny/python-coverage-comment-action-badge.json'
For more information check: https://httpstatuses.com/404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/subprocess.py", line 16, in run
    return subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('git', 'clone', '***github.com/crazyscientist/osc-tiny.wiki.git', '.')' returned non-zero exit status 128.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/subprocess.py", line 32, in _git
    return run(
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/subprocess.py", line 24, in run
    raise SubProcessError("/n".join([exc.stdout, exc.stderr])) from exc
coverage_comment.subprocess.SubProcessError: /nCloning into '.'...
fatal: remote error: access denied or repository not exported: /d/nw/d1/86/6a/195882036/161181449.wiki.git


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/coverage_comment", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/main.py", line 37, in main
    exit_code = action(
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/main.py", line 69, in action
    return generate_comment(
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/main.py", line 105, in generate_comment
    previous_coverage_data_file = wiki.get_file_contents(
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/wiki.py", line 95, in get_file_contents
    with cloned_wiki(repository, git, github_token) as wiki_dir:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/wiki.py", line 34, in cloned_wiki
    raise exc
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/wiki.py", line 26, in cloned_wiki
    git.clone(
  File "/usr/local/lib/python3.10/site-packages/coverage_comment/subprocess.py", line 39, in _git
    raise GitError from exc
coverage_comment.subprocess.GitError
```

**Comment by crazyscientist** [comment]
For reference, this is the PR where the comment cannot be added to: https://github.com/crazyscientist/osc-tiny/pull/79

**Comment by kieferro** [comment]
Hello, we are in the process of rebuilding the action. Therefore everything is a bit messed up at the moment, sorry for the inconvenience.
We are building a third version of the action. However, there are currently still some problems with this one, so I would recommend that you use the second version instead. They do exactly the same thing, but store the data in a different way. For the docs of the second version you have to look [here](https://github.com/ewjoachim/python-coverage-comment-action/blob/v2/README.md). The setup is a bit different (you have to set up a wiki, for example). In addition, there could be the problem that you only add the action via a pull request and therefore no basic data is available for comparison before you merge. The problem and the solution are described in more detail in #15.
If you'd rather wait for the third version, which works with its own branch instead of the wiki, I'll be happy to ping you when we've solved all the problems.
Sorry again for the inconvenience. I hope this helps.

**Comment by crazyscientist** [comment]
@kieferro Thank you for the quick reply. I'm in no hurry and would appreciate to be one of your beta testers :grin:

**Comment by kieferro** [comment]
Ok, then I'll just ping you when we're ready for the tests :smiley:

**Comment by kieferro** [comment]
@crazyscientist The third version of the action should work now. Everything described [here](https://github.com/marketplace/actions/python-coverage-comment) should be correct and work (note that there was a change in the documentation: You must always use `ewjoachim/python-coverage-comment-action@v3` for the third version, instead of `ewjoachim/python-coverage-comment-action@v2` as it was written before).
I will close this issue for now. If you still run into problems, feel free to reopen or open a new issue.

**Comment by crazyscientist** [comment]
Thank you, I now got a comment on the PR and an email notification :slightly_smiling_face:
